apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-image-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-image
  template:
    metadata:
      labels:
        app: my-image
    spec:
      containers:
        - name: my-image
          image: wassimpoly/my-image:latest
          ports:
            - containerPort: 8080
